version: '3.8'

services:
  app:
    container_name: bot
    environment:
      - SHELL=bash
      - NODE_ENV=production
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
